# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-deposits
#   namespace: nodejs-dev
# spec:
#   ingressClassName: nginx
#   # rules:
#   # - host: dev.wabank.org
#   #   http:
#   #     paths:
#   #     - path: /
#   #       backend:
#   #         serviceName: wabank-svc
#   #         servicePort: 3000